/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


/**
 * Event generated when an object enters a window.
 *
 * @event module:pointerdetector#WindowIn
 *
 * @type {module:pointerdetector#event:Media}
 *
 * @property {external:String} windowId
 *  Opaque String indicating the id of the window entered
 */

/**
 * Event generated when an object exits a window.
 *
 * @event module:pointerdetector#WindowOut
 *
 * @type {module:pointerdetector#event:Media}
 *
 * @property {external:String} windowId
 *  Opaque String indicating the id of the window entered
 */
