/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */


/**
 * Event generated when an object enters a window.
 *
 * @event module:pointerdetector#WindowIn
 *
 * @type {module:pointerdetector#event:Media}
 *
 * @property {external:String} windowId
 *  Opaque String indicating the id of the window entered
 */

/**
 * Event generated when an object exits a window.
 *
 * @event module:pointerdetector#WindowOut
 *
 * @type {module:pointerdetector#event:Media}
 *
 * @property {external:String} windowId
 *  Opaque String indicating the id of the window entered
 */
